all: meme.owo meme.uwu meme.uguu

%.owo:
	# $@ refers to full target filename (meme.owo)
	echo $@

%.uwu:
	# $* refers to target name without suffix (meme)
	echo $*

%.uguu:
	# $< refers to file change that caused target to trigger
	# should be nothing
	echo $<
